myQs = {
24: {"problem": ["There is a list = [0,1,2,3], what is at index 4?"], "answer": "3"},
25: {"problem": ["How do a dictionary and list differ?"], "answer": "order"},
26: {"problem": ["What boolean is equivalent to 0?"], "answer": "false"},
27: {"problem": ["What boolean is equivalent to 1?"], "answer": "true"},
28: {"problem": ["How do you turn a string into a list ordered by word?"], "answer": "string.split()"},
29: {"problem": ["How do you make strings lowercase?"], "answer": "string.lower()"},
30: {"problem": ["How do you make strings uppercase?"], "answer": "string.upper()"},
31: {"problem": ["What do you use to access libraries?"], "answer": "import"},
32: {"problem": ["What kind of loop can accidentally be infinite?"], "answer": "while"},
33: {"problem": ["What boolean is the result of (not 3=2)?"], "answer": "true"},
34: {"problem": ["What boolean is the result of (3=3 or 3=2)?"], "answer": "true"},
35: {"problem": ["What boolean is the result of (5 < 3 and 3 > 5)?"], "answer": "false"},
36: {"problem": ["What library is used for math functions?"], "answer": "math"},
37: {"problem": ["How do you import everything from a library?"], "answer": "*"},
38: {"problem": ["Are ranges inclusive?"], "answer": "no"},
39: {"problem": ["How do you get the length of a list?"], "answer": "len"},
40: {"problem": ["How do you make a list from a string?"], "answer": "list"},
41: {"problem": ["What do you use to get the maximum value from a list?"], "answer": "max"},
42: {"problem": ["What do you do to get the minimum value from a list?"], "answer": "min"},
43: {"problem": ["What is the length of this list: [0,1,2,3,4]?"], "answer": "5"},
44: {"problem": ["How many indices are in this list: [0,1,1,2]?"], "answer": "4"},
45: {"problem": ["What is the third index of this list: [9,4,6,7]?"], "answer": "7"},
46: {"problem": ["How do you add things to a list?"], "answer": "list.append"},
47: {"problem": ["What operator do you use to concatenate strings?"], "answer": "+"},
48: {"problem": ["x = 12",
                 "x = pow(x, 2)",
                 "print x"],"answer": ""}
}
